version: 0.0.1

services:
  app:
    container_name: emp-backend-app
    dockerfile: ./docker/go/Dockerfile


  postgres:
    container_name: postgres
    build:
       context: ./postgres

    ports: $(POSTGRES_PORT):5432
    environment:
      POSTGRES_USER: $(POSTGRES_USER)
      POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
      POSTGRES_DB: $(POSTGRES_DB)
    volumes:
      -./postgres:/var/lib/postgresql/data


volumes:
  db_data: