env: "local" # "prod/dev"
#storage_path: "./storage/app.db"
server:
  port: 8000
  token_ttl: 1h
  timeout: 1h
token_ttl: 1h

#database:
#  host: "localhost"
#  port: "5432"
#  user: "postgres"
#  password: "postgres"
#  name: "emp"